image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

stages:
  - build
  - test
  - run

variables:
    LCG_VERSION: "LCG_99"
    LCG_ARCHITECTURE: x86_64-centos7-clang10-opt

.build_job_matrix:
  parallel:
    matrix:
      - TARGET: [CPU, THREADS, OPENMP]
        BUILD_TYPE: [RelWithDebInfo, Debug]

.test_job_matrix:
  parallel:
    matrix:
      - TARGET: [CPU, THREADS, OPENMP]
        BUILD_TYPE: [RelWithDebInfo, Debug]

.run_job_matrix:
  parallel:
    matrix:
      -TARGET: [CPU, THREADS, OPENMP]
      BUILD_TYPE:
        - Release

build:
  stage: build
  extends: .build_job_matrix
  tags:
    - cvmfs
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh ${LCG_VERSION} ${LCG_ARCHITECTURE}
    - mkdir build_${TARGET}_${BUILD_TYPE}
    - cd build_${TARGET}_${BUILD_TYPE}
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DTARGET_BACKEND=${TARGET} ..
    - make
    - cd ..
  artifacts:
    paths:
      - build_${TARGET}_${BUILD_TYPE}/ABSimRun
    expire_in: 1 week

test:
  stage: test
  extends: .test_job_matrix
  tags:
    - cvmfs
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh ${LCG_VERSION} ${LCG_ARCHITECTURE}
    - ./build_${TARGET}_${BUILD_TYPE}/ABSimRun

run:
  stage: run
  extends: .run_job_matrix
  tags:
    - cvmfs
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh ${LCG_VERSION} ${LCG_ARCHITECTURE}
    - - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh ${LCG_VERSION} ${LCG_ARCHITECTURE}
    - mkdir build_${TARGET}_${BUILD_TYPE}
    - cd build_${TARGET}_${BUILD_TYPE}
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DTARGET_BACKEND=${TARGET} ..
    - make
    - cd ..
    - ./build_${TARGET}_${BUILD_TYPE}/ABSimRun

