image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

stages:
  - build
  - test
  - run

build:
  stage: build
  tags:
    - cvmfs
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_97python3 x86_64-centos7-clang8-opt
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON ..
    - make
    - cd ..
  artifacts:
    paths:
      - build/*

test:
  stage: test
  tags:
    - cvmfs
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_97python3 x86_64-centos7-clang8-opt
    - ./build/tests/Test

run:
  stage: run
  tags:
    - cvmfs
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_97python3 x86_64-centos7-clang8-opt
    - ./build/ABSimRun

